excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://sirahngelu.github.io
title: sirahngelu
tagline: nek iyo mosok orao, nek ora mosok iyoo.
description: Catetan web kanggo mbiasakne boso jowo.
paginate: 7